layout_spectrum: 0.495221
typography_spectrum: 0.7040715
color:
  saturation: 0.6042998
  brandStrength: 0.750393
  lightness: 0.7258064
  rhythmicContrast: 0.681932
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: ruzaini
